using UnityEngine;
using UnityEngine.UI;

public class TestPhase4
{
    /// <summary>Send a nav goal to the farthest Target_* marker; coins + path should appear.</summary>
    public static string Drive()
    {
        var bridge = WheelchairStateBridge.Instance;
        var cal = RoomCalibrationManager.Instance;
        if (bridge == null || cal == null) return "missing bridge/calibration";

        string best = null;
        float bestDist = -1f;
        foreach (var name in new[] { "Target_Kitchen", "Target_Bathroom", "Target_Bedroom", "Target_LivingRoom" })
        {
            if (!cal.TryGetRoomPosition(name, out Vector3 p)) continue;
            float d = (p - bridge.transform.position).sqrMagnitude;
            if (d > bestDist) { bestDist = d; best = name; }
        }
        if (best == null) return "no calibrated rooms";

        cal.TryGetRoomPosition(best, out Vector3 goal);
        bridge.SendNavigationGoal(goal);
        return "goal=" + best + " at " + goal + " " + Snapshot();
    }

    public static string Snapshot()
    {
        var score = ScoreManager.Instance;
        var line = Object.FindObjectOfType<PathVisualizer>(true);
        var lr = line != null ? line.GetComponent<LineRenderer>() : null;
        int activeCoins = 0;
        foreach (var c in Object.FindObjectsOfType<Coin>(true))
            if (c.IsActive) activeCoins++;
        return "| points=" + (score != null ? score.CurrentPoints.ToString() : "NO-SCOREMGR")
             + " lineVerts=" + (lr != null ? lr.positionCount.ToString() : "NO-LINE")
             + " activeCoins=" + activeCoins
             + " themeMgr=" + (ThemeManager.Instance != null)
             + " shop=" + (Object.FindObjectOfType<ThemeShopController>(true) != null);
    }

    /// <summary>Open pause overlay then the shop via the real buttons (UI path test).</summary>
    public static string OpenShop()
    {
        var gmm = GameModeManager.Instance;
        if (gmm == null) return "no GameModeManager";
        gmm.OpenPause();
        var shopBtn = GameObject.Find("GameHUDCanvas").transform
            .Find("PauseOverlayPanel/SettingsBox/Btn_ThemeShop").GetComponent<Button>();
        if (!shopBtn.interactable) return "shop button not interactable";
        shopBtn.onClick.Invoke();
        var shop = Object.FindObjectOfType<ThemeShopController>(true);
        return "panelActive=" + shop.panel.activeSelf + " cards=" + (shop.panel.GetComponentsInChildren<Button>(false).Length - 1);
    }

    /// <summary>Grant points, buy + equip NEON GREEN, verify wall material swapped.</summary>
    public static string BuyTheme()
    {
        var score = ScoreManager.Instance;
        var tm = ThemeManager.Instance;
        if (score == null || tm == null) return "missing managers";
        if (score.CurrentPoints < 10) score.AddPoints(10 - score.CurrentPoints);

        bool bought = tm.TryPurchase("NEON GREEN");
        tm.Equip("NEON GREEN");

        var map = GameObject.Find("AutoGeneratedMap");
        string wallMat = "none", floorMat = "none";
        foreach (Transform child in map.transform)
        {
            var r = child.GetComponent<Renderer>();
            if (r == null) continue;
            if (child.name == "AutoFloor") floorMat = r.sharedMaterial.name;
            else wallMat = r.sharedMaterial.name;
        }
        return "bought=" + bought + " owned=" + tm.IsOwned("NEON GREEN") + " equipped=" + tm.IsEquipped("NEON GREEN")
             + " floor=" + floorMat + " wall=" + wallMat + " pointsLeft=" + score.CurrentPoints;
    }

    /// <summary>Reset back to the default theme + clear test points so trials start clean.</summary>
    public static string ResetEconomy()
    {
        var tm = ThemeManager.Instance;
        if (tm != null) tm.Equip("CLASSIC YELLOW");
        GamePrefs.SetInt(GamePrefs.CurrentPoints, 0);
        GamePrefs.DeleteKey(GamePrefs.OwnedThemes);
        GamePrefs.SetString(GamePrefs.EquippedTheme, "CLASSIC YELLOW");
        return "reset done " + Snapshot();
    }
}
