using UnityEngine;
using Unity.AI.Navigation; // We need this to command the NavMesh!

public class MapGenerator : MonoBehaviour
{
    [Header("Map Data")]
    public Texture2D occupancyGrid;
    public GameObject wallPrefab;

    [Header("Settings")]
    public float wallHeight = 4f; // Makes the walls much taller
    
    [Header("Auto-Baking")]
    // We will drag the NavMeshSurface component into this slot in the Inspector
    public NavMeshSurface navMeshSurface; 

    void Start()
    {
        Generate3DMap();
    }

    public void Generate3DMap()
    {
        GameObject mapParent = new GameObject("AutoGeneratedMap");

        // 1. Calculate the offsets to center the map at (0,0)
        float offsetX = occupancyGrid.width / 2f;
        float offsetZ = occupancyGrid.height / 2f;

        // 2. BUILD THE FLOOR
        GameObject floor = GameObject.CreatePrimitive(PrimitiveType.Plane);
        floor.name = "AutoFloor";
        // A default Unity plane is 10x10 units, so we divide by 10 to fit our map exactly
        floor.transform.localScale = new Vector3(occupancyGrid.width / 10f, 1, occupancyGrid.height / 10f);
        floor.transform.position = Vector3.zero; // Put it at the exact center
        floor.transform.parent = mapParent.transform;

        // 3. BUILD THE WALLS
        for (int x = 0; x < occupancyGrid.width; x++)
        {
            for (int y = 0; y < occupancyGrid.height; y++)
            {
                Color pixelColor = occupancyGrid.GetPixel(x, y);

                // If pixel is black/dark
                if (pixelColor.grayscale < 0.5f)
                {
                    // Apply our center offset!
                    Vector3 spawnPosition = new Vector3(x - offsetX, wallHeight / 2f, y - offsetZ);

                    GameObject newWall = Instantiate(wallPrefab, spawnPosition, Quaternion.identity);
                    
                    // Stretch the cube on the Y axis to make it a tall wall
                    newWall.transform.localScale = new Vector3(1f, wallHeight, 1f);
                    newWall.transform.parent = mapParent.transform;
                }
            }
        }

        Debug.Log("Map Built and Centered!");

        // 4. AUTO-BAKE THE NAVMESH
        if (navMeshSurface != null)
        {
            navMeshSurface.BuildNavMesh();
            Debug.Log("NavMesh Automatically Baked!");
        }
    }
}