using UnityEngine;
using Unity.AI.Navigation;
using System.IO;

public class MapGenerator : MonoBehaviour
{
    [Header("Map Data")]
    [Tooltip("Map file under StreamingAssets/Maps. Drop a new PNG there and set this name to swap maps - no import settings required.")]
    public string mapFileName = "mymap_test4.png";
    [Tooltip("Fallback occupancy grid, used only if the StreamingAssets file is missing.")]
    public Texture2D occupancyGrid;
    public GameObject wallPrefab;

    [Header("Aesthetics")]
    public float wallHeight = 10f; // Defaulted to 10 for the tall walls
    public Material floorMaterial; // Slot for the floor material

    [Header("Generation")]
    [Tooltip("Pixels per wall cell. 1 = one cube per pixel (crisp but heavy). Higher = fewer, chunkier cubes. Uses OR-reduction so walls only thicken, never develop gaps.")]
    public int cellSize = 2;
    [Tooltip("A pixel counts as a wall when its grayscale is below this value.")]
    [Range(0f, 1f)] public float wallThreshold = 0.5f;
    [Tooltip("Drop wall cells that have fewer than this many occupied orthogonal neighbors (removes lone speckles / stray dots on the floor). 0 disables de-speckling.")]
    public int minNeighbors = 1;

    [Header("Auto-Baking")]
    public NavMeshSurface navMeshSurface;

    // Exposed for verification/debugging after a build.
    public static int LastWallCount;

    // CHANGED: Awake runs before Start, ensuring the floor exists before the wheelchair drops!
    void Awake()
    {
        Generate3DMap();
    }

    public void Generate3DMap()
    {
        Texture2D grid = LoadOccupancyGrid();
        if (grid == null)
        {
            Debug.LogError("MapGenerator: no occupancy grid available (StreamingAssets file missing and no fallback assigned).");
            return;
        }

        GameObject mapParent = new GameObject("AutoGeneratedMap");

        int w = grid.width;
        int h = grid.height;
        float offsetX = w / 2f;
        float offsetZ = h / 2f;

        // 1. BUILD THE FLOOR (default Unity plane is 10x10 units, so divide by 10 to fit)
        GameObject floor = GameObject.CreatePrimitive(PrimitiveType.Plane);
        floor.name = "AutoFloor";
        floor.transform.localScale = new Vector3(w / 10f, 1, h / 10f);
        floor.transform.position = Vector3.zero;
        floor.transform.parent = mapParent.transform;
        if (floorMaterial != null)
            floor.GetComponent<Renderer>().material = floorMaterial;

        // 2. OCCUPANCY -> CELL GRID (block-based, OR-reduced so walls stay watertight)
        int cell = Mathf.Max(1, cellSize);
        Color[] pixels = grid.GetPixels(); // single read instead of width*height GetPixel calls
        int cols = (w + cell - 1) / cell;
        int rows = (h + cell - 1) / cell;
        bool[,] occ = new bool[cols, rows];
        for (int cxi = 0; cxi < cols; cxi++)
        {
            for (int cyi = 0; cyi < rows; cyi++)
            {
                bool occupied = false;
                int bx = cxi * cell, by = cyi * cell;
                for (int ix = bx; ix < bx + cell && ix < w && !occupied; ix++)
                {
                    for (int iy = by; iy < by + cell && iy < h; iy++)
                    {
                        if (pixels[ix + iy * w].grayscale < wallThreshold) { occupied = true; break; }
                    }
                }
                occ[cxi, cyi] = occupied;
            }
        }

        // 3. DE-SPECKLE: drop isolated cells with too few occupied orthogonal neighbors.
        if (minNeighbors > 0)
        {
            bool[,] cleaned = new bool[cols, rows];
            for (int cxi = 0; cxi < cols; cxi++)
            {
                for (int cyi = 0; cyi < rows; cyi++)
                {
                    if (!occ[cxi, cyi]) continue;
                    int n = 0;
                    if (cxi > 0 && occ[cxi - 1, cyi]) n++;
                    if (cxi < cols - 1 && occ[cxi + 1, cyi]) n++;
                    if (cyi > 0 && occ[cxi, cyi - 1]) n++;
                    if (cyi < rows - 1 && occ[cxi, cyi + 1]) n++;
                    cleaned[cxi, cyi] = n >= minNeighbors;
                }
            }
            occ = cleaned;
        }

        // 4. BUILD THE WALLS
        int wallCount = 0;
        for (int cxi = 0; cxi < cols; cxi++)
        {
            for (int cyi = 0; cyi < rows; cyi++)
            {
                if (!occ[cxi, cyi]) continue;
                float cx = cxi * cell + cell / 2f;
                float cz = cyi * cell + cell / 2f;
                Vector3 spawnPosition = new Vector3(cx - offsetX, wallHeight / 2f, cz - offsetZ);

                GameObject newWall = Instantiate(wallPrefab, spawnPosition, Quaternion.identity);
                newWall.transform.localScale = new Vector3(cell, wallHeight, cell);
                newWall.transform.parent = mapParent.transform;
                wallCount++;
            }
        }

        LastWallCount = wallCount;
        Debug.Log("Map Built and Centered! Walls: " + wallCount);

        // 5. AUTO-BAKE THE NAVMESH
        // Self-heal: the inspector reference can be lost on save/reload, so fall back to the
        // NavMeshSurface on this same GameObject.
        if (navMeshSurface == null) navMeshSurface = GetComponent<NavMeshSurface>();
        if (navMeshSurface != null)
        {
            navMeshSurface.BuildNavMesh();
            Debug.Log("NavMesh Automatically Baked!");
        }
        else
        {
            Debug.LogWarning("No NavMeshSurface found; the avatar will have no NavMesh to navigate.");
        }
    }

    /// <summary>
    /// Loads the occupancy grid from StreamingAssets/Maps/<mapFileName> at runtime.
    /// Texture2D.LoadImage yields a readable, uncompressed, no-mip texture, which
    /// sidesteps all import-setting issues. Falls back to the serialized texture.
    /// </summary>
    Texture2D LoadOccupancyGrid()
    {
        string path = Path.Combine(Application.streamingAssetsPath, "Maps", mapFileName);
        if (File.Exists(path))
        {
            byte[] data = File.ReadAllBytes(path);
            Texture2D tex = new Texture2D(2, 2, TextureFormat.RGBA32, false);
            if (tex.LoadImage(data)) // resizes to the image; readable + uncompressed + no mips
            {
                tex.filterMode = FilterMode.Point;
                Debug.Log("MapGenerator: loaded map '" + mapFileName + "' (" + tex.width + "x" + tex.height + ") from StreamingAssets.");
                return tex;
            }
            Debug.LogWarning("MapGenerator: could not decode '" + path + "'; using fallback texture.");
        }
        else
        {
            Debug.LogWarning("MapGenerator: no map file at '" + path + "'; using fallback serialized texture.");
        }
        return occupancyGrid;
    }
}
