using UnityEngine;
using Unity.AI.Navigation; 

public class MapGenerator : MonoBehaviour
{
    [Header("Map Data")]
    public Texture2D occupancyGrid;
    public GameObject wallPrefab;

    [Header("Aesthetics")]
    public float wallHeight = 10f; // Defaulted to 10 for the tall walls
    public Material floorMaterial; // ADDED: Slot for your blue/green floor material

    [Header("Generation")]
    [Tooltip("Pixels per wall cell. 1 = one cube per pixel (crisp but heavy). Higher = fewer, chunkier cubes. Uses OR-reduction so walls only thicken, never develop gaps.")]
    public int cellSize = 2;
    [Tooltip("A pixel counts as a wall when its grayscale is below this value.")]
    [Range(0f, 1f)] public float wallThreshold = 0.5f;

    [Header("Auto-Baking")]
    public NavMeshSurface navMeshSurface;

    // Exposed for verification/debugging after a build.
    public static int LastWallCount;

    // CHANGED: Awake runs before Start, ensuring the floor exists before the wheelchair drops!
    void Awake()
    {
        Generate3DMap();
    }

    public void Generate3DMap()
    {
        GameObject mapParent = new GameObject("AutoGeneratedMap");

        // 1. Calculate the offsets to center the map at (0,0)
        float offsetX = occupancyGrid.width / 2f;
        float offsetZ = occupancyGrid.height / 2f;

        // 2. BUILD THE FLOOR
        GameObject floor = GameObject.CreatePrimitive(PrimitiveType.Plane);
        floor.name = "AutoFloor";
        // A default Unity plane is 10x10 units, so we divide by 10 to fit our map exactly
        floor.transform.localScale = new Vector3(occupancyGrid.width / 10f, 1, occupancyGrid.height / 10f);
        floor.transform.position = Vector3.zero; // Put it at the exact center
        floor.transform.parent = mapParent.transform;

        // ADDED: Paint the floor with our custom material!
        if (floorMaterial != null)
        {
            floor.GetComponent<Renderer>().material = floorMaterial;
        }

        // 3. BUILD THE WALLS (block-based, OR-reduced so walls stay watertight)
        int cell = Mathf.Max(1, cellSize);
        int w = occupancyGrid.width;
        int h = occupancyGrid.height;
        Color[] pixels = occupancyGrid.GetPixels(); // one read instead of width*height GetPixel calls
        int wallCount = 0;

        for (int bx = 0; bx < w; bx += cell)
        {
            for (int by = 0; by < h; by += cell)
            {
                // A cell is a wall if ANY pixel in the block is dark (prevents thin walls vanishing).
                bool occupied = false;
                for (int ix = bx; ix < bx + cell && ix < w && !occupied; ix++)
                {
                    for (int iy = by; iy < by + cell && iy < h; iy++)
                    {
                        if (pixels[ix + iy * w].grayscale < wallThreshold) { occupied = true; break; }
                    }
                }
                if (!occupied) continue;

                // Center of the block, with our map-centering offset applied.
                float cx = bx + cell / 2f;
                float cz = by + cell / 2f;
                Vector3 spawnPosition = new Vector3(cx - offsetX, wallHeight / 2f, cz - offsetZ);

                GameObject newWall = Instantiate(wallPrefab, spawnPosition, Quaternion.identity);
                // Footprint = one cell, stretched tall on Y.
                newWall.transform.localScale = new Vector3(cell, wallHeight, cell);
                newWall.transform.parent = mapParent.transform;
                wallCount++;
            }
        }

        LastWallCount = wallCount;
        Debug.Log("Map Built and Centered! Walls: " + wallCount);

        // 4. AUTO-BAKE THE NAVMESH
        // Self-heal: the inspector reference can be lost on save/reload, so fall back to the
        // NavMeshSurface on this same GameObject.
        if (navMeshSurface == null) navMeshSurface = GetComponent<NavMeshSurface>();
        if (navMeshSurface != null)
        {
            navMeshSurface.BuildNavMesh();
            Debug.Log("NavMesh Automatically Baked!");
        }
        else
        {
            Debug.LogWarning("No NavMeshSurface found; the avatar will have no NavMesh to navigate.");
        }
    }
}