using System;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class ThemeDefinition
{
    public string themeName;
    public int cost;
    public Material floorMaterial;
    public Material wallMaterial;
}

/// <summary>
/// Unlockable high-contrast theme catalog. Equipping swaps sharedMaterial on the
/// generated floor and every instanced wall - a one-time loop that creates no
/// per-instance material copies, so SRP batching stays intact. Ownership and the
/// equipped theme persist in PlayerPrefs; themes[0] is the free default.
/// </summary>
public class ThemeManager : MonoBehaviour
{
    public static ThemeManager Instance { get; private set; }

    public ThemeDefinition[] themes;

    [Serializable]
    private class OwnedData
    {
        public List<string> names = new List<string>();
    }

    private OwnedData owned;
    private string equipped;

    void Awake()
    {
        Instance = this;
        owned = GamePrefs.GetJson<OwnedData>(GamePrefs.OwnedThemes) ?? new OwnedData();
        string defaultName = themes != null && themes.Length > 0 ? themes[0].themeName : "";
        if (!owned.names.Contains(defaultName)) owned.names.Add(defaultName);
        equipped = GamePrefs.GetString(GamePrefs.EquippedTheme, defaultName);
    }

    void OnDestroy()
    {
        MapGenerator.OnMapReady -= ApplyToScene;
        if (Instance == this) Instance = null;
    }

    void Start()
    {
        // Re-skin the generated map every time it (re)builds, so a non-default
        // theme survives scene reloads without a visible material swap.
        if (MapGenerator.IsMapReady) ApplyToScene();
        MapGenerator.OnMapReady += ApplyToScene;
    }

    public bool IsOwned(string themeName) => owned.names.Contains(themeName);
    public bool IsEquipped(string themeName) => equipped == themeName;

    public bool TryPurchase(string themeName)
    {
        ThemeDefinition def = Find(themeName);
        if (def == null) return false;
        if (IsOwned(themeName)) return true;
        if (ScoreManager.Instance == null || !ScoreManager.Instance.TrySpend(def.cost)) return false;

        owned.names.Add(themeName);
        GamePrefs.SetJson(GamePrefs.OwnedThemes, owned);
        return true;
    }

    public void Equip(string themeName)
    {
        if (!IsOwned(themeName) || Find(themeName) == null) return;
        equipped = themeName;
        GamePrefs.SetString(GamePrefs.EquippedTheme, themeName);
        ApplyToScene();
    }

    private void ApplyToScene()
    {
        ThemeDefinition def = Find(equipped);
        if (def == null) return;

        GameObject mapParent = GameObject.Find("AutoGeneratedMap");
        if (mapParent == null) return;

        foreach (Transform child in mapParent.transform)
        {
            var r = child.GetComponent<Renderer>();
            if (r == null) continue;
            r.sharedMaterial = child.name == "AutoFloor" ? def.floorMaterial : def.wallMaterial;
        }
        Debug.Log("[ThemeManager] Applied theme '" + equipped + "'.");
    }

    private ThemeDefinition Find(string themeName)
    {
        if (themes == null) return null;
        foreach (ThemeDefinition t in themes)
            if (t.themeName == themeName) return t;
        return null;
    }
}
